In [2]:
#!pip install nltk

  Using cached nltk-3.6.2-py3-none-any.whl (1.5 MB)
  Using cached tqdm-4.60.0-py2.py3-none-any.whl (75 kB)


In [1]:
import nltk

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [40]:
import pandas as pd
import numpy as np

In [20]:
message=pd.read_table(r"C:\Users\bansil\Downloads\smsspamcollection\SMSSpamCollection",sep='\t',
                                                                    names=['labels','messages'])

In [22]:
message.head()

labels                                           messages
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [25]:
# Data cleaning and preprocessing
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [31]:
corpus=[]
for i in range(0, len(message)):
    review=re.sub('[^a-zA-Z]',' ',message['messages'][i])
    review=review.lower()
    review=review.split()
    
    review= [ps.stem(word) for word in review if not word in stopwords.words("english")]
    review=' '.join(review)
    corpus.append(review)

In [34]:
# Create a BagofWord Model
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)
x=cv.fit_transform(corpus).toarray()

In [43]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [45]:
y=pd.get_dummies(message['labels'])
y=y.iloc[:,1].values

In [52]:
# Training the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2,random_state=42)

In [54]:
# classification using naive-bayes
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(x_train,y_train)

In [55]:
y_pred=spam_detect_model.predict(x_test)

In [56]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [57]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [60]:
# checking where our model is confusing
from sklearn.metrics import confusion_matrix
confusion_m=confusion_matrix(y_test,y_pred)

In [61]:
confusion_m

array([[955,  11],
       [  7, 142]], dtype=int64)

In [62]:
# checking the accuracy score
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [63]:
accuracy

0.9838565022421525